# Supabase self-host containers should started before running this compose file
# You can start it with:
#   supabase start

services:
  powersync:
    container_name: powersync_demo
    restart: unless-stopped
    env_file:
      - ../.env.local
    image: journeyapps/powersync-service:latest
    volumes:
      - ./powersync.yaml:/app/powersync.yaml
    networks:
      - supabase_network_powersync
    ports:
      - ${PS_PORT}:${PS_PORT}

networks:
  supabase_network_powersync:
    external: true